import { ComponentFormType } from "../../../../components/Forms/enum/ComponentFormType.enum";
import { SelectInputDialogType } from "../../../../components/SelectInputDialog/enum/SelectInputDialogType.type";
import { CreateTrainingFormsType } from "../type/CreateTrainingFormsType.type";

export const CreateTrainingFormsSchema: CreateTrainingFormsType = {
  information: {
    name: {
      id: "name",
      name: "name",
      fullWidth: true,
      label: "Name",
      placeholder: "Name",
      required: true,
      errorMessage: "name required",
      value: "",
      disabled: false,
      type: "text",
      componentType: ComponentFormType.INPUT_TEXT,
      autoFocus: false,
      autoComplete: "",
      validate: {
        pattern: {
          value: /^/,
          message: "",
        },
      },
      options: [],
    },
    date: {
      id: "date",
      name: "date",
      fullWidth: true,
      label: {
        start: "Start Date",
        end: "End Date",
      },
      placeholder: "Date",
      required: false,
      errorMessage: "date required",
      value: [null, null],
      // value: [],
      // value: [new Date('2022-04-17'), new Date('2022-04-17')],
      disabled: false,
      type: "text",
      componentType: ComponentFormType.INPUT_DATE_RANGE,
      autoFocus: false,
      autoComplete: "",
      validate: {
        pattern: {
          value: /^/,
          message: "",
        },
      },
      options: [],
    },
    duration: {
      id: "duration",
      name: "duration",
      fullWidth: true,
      label: "Duration",
      placeholder: "Duration",
      required: true,
      errorMessage: "duration required",
      value: "",
      disabled: false,
      type: "number",
      componentType: ComponentFormType.INPUT_NUMBER_FORMAT,
      autoFocus: false,
      autoComplete: "",
      validate: {
        pattern: {
          value: /^/,
          message: "",
        },
      },
      options: [],
    },
    budgetCode: {
      id: "budgetCode",
      name: "budgetCode",
      fullWidth: true,
      label: "Budget Code",
      placeholder: "Budget Code",
      required: true,
      errorMessage: "budget ccode required",
      // value: { id: '', label: '' },
      value: null,
      disabled: false,
      type: "text",
      componentType: ComponentFormType.INPUT_AUTOCOMPLETE_SINGLE,
      autoFocus: false,
      autoComplete: "",
      validate: {
        pattern: {
          value: /^/,
          message: "",
        },
      },
      options: [],
    },
    type: {
      id: "type",
      name: "type",
      fullWidth: true,
      label: "Training Type",
      placeholder: "Training Type",
      required: true,
      errorMessage: "training type required",
      value: "",
      disabled: false,
      type: "select",
      componentType: ComponentFormType.INPUT_SELECT_MODAL,
      autoFocus: false,
      autoComplete: "",
      validate: {
        pattern: {
          value: /^/,
          message: "",
        },
      },
      options: [],
      SelectInputDialogType: SelectInputDialogType.TRAINING_TYPE,
    },
    objective: {
      id: "objective",
      name: "objective",
      fullWidth: true,
      label: "Training Objective",
      placeholder: "Training Objective",
      required: true,
      errorMessage: "training objective required",
      value: "",
      disabled: false,
      type: "text",
      componentType: ComponentFormType.INPUT_TEXT_AREA,
      autoFocus: false,
      autoComplete: "",
      validate: {
        pattern: {
          value: /^/,
          message: "",
        },
      },
      options: [],
    },
    participants: {
      id: "name",
      name: "participants",
      fullWidth: true,
      label: "Participants",
      placeholder: "Participants",
      required: true,
      errorMessage: "participants required",
      value: [],
      disabled: false,
      type: "text",
      componentType: ComponentFormType.INPUT_AUTOCOMPLETE_MULTIPLE,
      autoFocus: false,
      autoComplete: "",
      validate: {
        pattern: {
          value: /^/,
          message: "",
        },
      },
      options: [],
    },
  },
  vendor: [
    {
      name: {
        id: "name",
        name: "name",
        fullWidth: true,
        label: "Vendor Name",
        placeholder: "Vendor Name",
        required: true,
        errorMessage: "vendor name required",
        value: null,
        disabled: false,
        type: "text",
        componentType: ComponentFormType.INPUT_AUTOCOMPLETE_SINGLE,
        autoFocus: false,
        autoComplete: "",
        validate: {
          pattern: {
            value: /^/,
            message: "",
          },
        },
        options: [],
      },
      cost: {
        id: "cost",
        name: "cost",
        fullWidth: true,
        label: "Cost",
        placeholder: "Cost",
        required: true,
        errorMessage: "cost required",
        value: "",
        disabled: false,
        type: "text",
        componentType: ComponentFormType.INPUT_TEXT,
        autoFocus: false,
        autoComplete: "",
        validate: {
          pattern: {
            value: /^/,
            message: "",
          },
        },
        options: [],
      },
    },
  ],
};
