export enum ComponentFormType {
  INPUT_TEXT = 'INPUT_TEXT',
  INPUT_TEXT_AREA = 'INPUT_TEXT_AREA',
  INPUT_DROPDOWN = 'INPUT_DROPDOWN',
  INPUT_SELECT_MODAL = 'INPUT_SELECT_MODAL',
  INPUT_NUMBER_FORMAT = 'INPUT_NUMBER_FORMAT',
  INPUT_DATE_RANGE = 'INPUT_DATE_RANGE',
  INPUT_AUTOCOMPLETE_MULTIPLE = 'INPUT_AUTOCOMPLETE_MULTIPLE',
  INPUT_AUTOCOMPLETE_SINGLE = 'INPUT_AUTOCOMPLETE_SINGLE',
}
